### ISSUE TITLE
Formulas suddenly get mangled (on save?)

### ISSUE THREAD

**Issue by kyounes** [ljcoder2015/obsidian-sheet-plus#10]
In the same sheet as bug #9, formulas get mangled either on exit (when I click on another obsidian tab), or on re-entry (when I click on the spreadsheet tab again). Specifically, the multiply sign '*' gets replaced by an underscore sign '_' in a number of cells, causing the formula to fail of course.

![image](https://github.com/ljcoder2015/obsidian-excel-plus/assets/6969634/a4ea84a3-ae82-49d9-b902-b489f9215eb4)

**Comment by ljcoder2015** [comment]
fix 1.2.1
