### ISSUE TITLE
Formulas missing when importing Excel

### ISSUE THREAD

**Issue by orvpagadua** [ljcoder2015/obsidian-sheet-plus#12]
**Describe the bug**
Formulas missing when importing Excel. 

**To Reproduce**
1. Create a Table with formulas on Excel. Save
2. Import to Obsidian and open the file

**Device (please complete the following information):**
 - OS: Mac OS
 - 14.5 (23F79)

**Obsidian 
 - Version 1.5.12

**Comment by ljcoder2015** [comment]
Does not support the import feature.
#8
