### ISSUE TITLE
Data Validations causes entire Obsidian app to be greyed-out

### ISSUE THREAD

**Issue by adivekar-utexas** [ljcoder2015/obsidian-sheet-plus#13]
**Describe the bug**

**To Reproduce**
1. Click on any cell
2. Click on "Data Validations" in right-click menu.

**Expected behavior**
You should be able to see the data validation panel, but it is instead blacked-out and not clickable. On pressing "Escape" key, you get back to the original view.

**Screenshots**
<img width="1603" alt="image" src="https://github.com/ljcoder2015/obsidian-sheet-plus/assets/71379271/22e68abc-3f96-4dbc-b6c9-ce6bed4aa566">

**Device (please complete the following information):**
 - OS: MacOS
 - Version: Ventura 13.5.2

**Obsidian (please complete the following information):**
 - Version: 1.5.12

**Comment by ljcoder2015** [comment]
This is a bug in the Excel plugin, which is no longer maintained. You can try the Sheet Plug plugin instead.

**Comment by adivekar-utexas** [comment]
Hi @ljcoder2015, do you mind publishing this plugin on Community plugins? I am planning to use it on my iphone as well, and it's not possible to load custom plugins from zip there AFAIK.

**Comment by adivekar-utexas** [comment]
It's also a bit confusing with the existing Excel plugin, I suggest adding a note on the Plugin page on Obsidian saying it is deprecated.

**Comment by ljcoder2015** [comment]
This plugin is under review
