### ISSUE TITLE
Documentation: How to set the height of an embedded table in Obsidian?

### ISSUE THREAD

**Issue by merlinuwe** [ljcoder2015/obsidian-sheet-plus#17]
I tried this

![image](https://github.com/ljcoder2015/obsidian-sheet-plus/assets/4138869/8178a1b1-490d-49b4-80ff-74dd89cabfa3)

and got this

![image](https://github.com/ljcoder2015/obsidian-sheet-plus/assets/4138869/e3d5ff7b-6869-4ea9-9614-31e9f15ec786)

An alternative would be to determine a table section. 

Column n to m.

Row a to b.

**Comment by ljcoder2015** [comment]
eg.
```
![[Excel 2024-06-05 13.41.50.univer#Sheet1|<1000>]]
```
For specific rules, please refer to the README.
