### ISSUE TITLE
How to create an excel sheet

### ISSUE THREAD

**Issue by DutchPete** [ljcoder2015/obsidian-sheet-plus#18]
I found the solution.

**Comment by amaharana** [comment]
What's the solution? I have installed the plugin but I can't figure out how to get Excel tables to show up in a note.

**Comment by DutchPete** [comment]
@amaharana your question suggests you know how to create an excel-style table with the plug-in.
Then, if you want to embed that table in a note, you do exactly the same as if you embed another note: you link to it `![[name of the excel file]]`. The exclamation mark in front of it indicates it shows the embedded table in your note.

**Comment by amaharana** [comment]
@DutchPete: I actually don't know how to invoke the plugin to create an excel-style table. I have installed the plugin but I don't see any obvious menu items or buttons to create an Excel table. Appreciate any pointer.

**Comment by DutchPete** [comment]
There are 2 ways to invoke:
1. there should be an icon in the narrow vertical ribbon strip on the left of the Obsidian screen. You can click on it to create an excel sheet;
2. by hitting the `CTRL+P` shortcut you'll get a list of options to choose from; type `excel` in there to create an excel sheet.

**Comment by amaharana** [comment]
My issue was the plugin was installed but not enabled. Didn't realize I had to enable it explicitly. All good now - I see the Excel icon on the left sidebar and command palette also has the option. Appreciate the help!
