### ISSUE TITLE
FEATURE REQUEST: embed link

### ISSUE THREAD

**Issue by DutchPete** [ljcoder2015/obsidian-sheet-plus#19]
Would be possible to embed a sheet in a note, just like one can embed a note or PDF in another note?

**Comment by ljcoder2015** [comment]
Of course, you can. The rules are as follows:
<img width="878" alt="image" src="https://github.com/ljcoder2015/obsidian-sheet-plus/assets/15226918/b331338f-0e99-466f-bb0f-dd9fab2e4146">

**Comment by DutchPete** [comment]
Thanks for your help.
Yes, that works ... partly. I cannot get the bit behind the pipe (D8:G14 etc. in your example) to work. So, what I get is this:

![image](https://github.com/ljcoder2015/obsidian-sheet-plus/assets/10794265/02705900-f7aa-4b8f-9285-c670816c0183)

I tried it with this: A1:E4 but nothing changes.
I tried 1-A:4-E, but no change either.
Also, I don't know what "sheet height" means — you use 1000 in your example, is that 1000 rows or what units?

**Comment by ljcoder2015** [comment]
The format might be incorrect. After selecting the area you want to reference, there is a button in the top right corner that can quickly generate the link.

Height refers to the window height displayed in the note. Try it out to understand better.

<img width="713" alt="image" src="https://github.com/ljcoder2015/obsidian-sheet-plus/assets/15226918/d25a1840-c6a9-43e5-bfb8-5eb598adecef">

**Comment by DutchPete** [comment]
The embed button works fine, it is much easier to use that than to try to the syntax.

As for the window height, I don't see any effect: I went from 300 to 10,000 (no comma) in steps but nothing changes.

**Comment by ljcoder2015** [comment]
After making changes, you need to reopen the file to see the effects.

**Comment by DutchPete** [comment]
Brilliant, works fine, many thanks.
Last question: is there a way to not show the column letters, row numbers, and the grey strip at the bottom? Should I make a separate feature request for it?

**Comment by ljcoder2015** [comment]
You can submit a feature request.

**Comment by DutchPete** [comment]
OK, done #22 .

**Comment by DutchPete** [comment]
There is a rule for sheet height: is there one for sheet width too?
If so, what is it?
If not, I shall submit a feature request.
