### ISSUE TITLE
Files flicker all the time

### ISSUE THREAD

**Issue by eric209** [ljcoder2015/obsidian-sheet-plus#21]
**Describe the bug**
When I create a new Excel file ,the file keeps flickering; even if I close the file and open it again, the issue persists。

**Screenshots**
![PixPin_2024-06-28_15-47-47](https://github.com/ljcoder2015/obsidian-sheet-plus/assets/29397511/d67ca299-f0ff-44c2-a7ab-0b5d64f96bed)

**Device (please complete the following information):**
 - system: windows11 

**Obsidian (please complete the following information):**
 - Version: 1.6.5

**Comment by aubreyz** [comment]
I have exactly the same problem - although at a slower rate.

**Comment by eric209** [comment]
After some testing, there was a conflict with the Update Time plugin. Uninstalling the plugin resolved the issue and everything is working normally now.

**Comment by ljcoder2015** [comment]
This issue occurs when the same file is opened in two tabs. Please avoid doing this.

**Comment by oo3mL** [comment]
> After some testing, there was a conflict with the Update Time plugin. Uninstalling the plugin resolved the issue and everything is working normally now.

Thanks for posting the solution. Saved me time on disabling plugins one by one. I just included my Excel folder in the excluded list within Update Time on Edit and all is well.
