### ISSUE TITLE
can not use in ob mobile could you solve it？

### ISSUE THREAD

**Issue by violentrant** [ljcoder2015/obsidian-sheet-plus#26]
can not use in ob mobile could you solve it？
the message is that
"Failed to load plugin sheet-plus"

**Comment by AndriiPetrovDev** [comment]
I see the same

**Comment by violentrant** [comment]
> Currently, this feature does not fully support mobile devices. We recommend using it on a PC for the best experience.

tjank u for u reply，parhaps i just I hope don't have to migrate all the functions to your phone, just read it, simply fill in the numbers or text, slide to select + sum, average, and save it. This will be much more user-friendly and can be used on all platforms. In the past, the old version of Excel could be opened on the mobile phone and read the file, but the swiping was not smooth, and the summing could not be selected efficiently.

**Comment by ljcoder2015** [comment]
fix 1.3.1
