### ISSUE TITLE
Cell (number) formatting does not work correctly

### ISSUE THREAD

**Issue by kyounes** [ljcoder2015/obsidian-sheet-plus#27]
When I try to set a cell or a column to a specific number format, the results are not as expected.

For example, if I have a column of numbers, and I choose to format the whole column as currency, use '$ ', 2 decimal digits, it might work at first, but as soon as I type in a new value in an empty cell in that same column, that value does not use the format I specified for that column. Even if I try after that to set the same formatting for that specific cell, it does not work.

**Comment by ljcoder2015** [comment]
fix 1.3.1
