### ISSUE TITLE
Suspected memory leak/mismanagement

### ISSUE THREAD

**Issue by vai** [ljcoder2015/obsidian-sheet-plus#31]
Enabling this plugin makes my Obsidian instance go from <500MiB of memory allocated, to over 20GiB in short order, even without opening any sheets pages.

NixOS/Linux. No other plugin I use behaves this way, and all are functional. This may also be related to the other issues I see for mobile stability, as they are memory constrained environments.

**Comment by lukeyewu** [comment]
same problem +1

**Comment by luzhe610** [comment]
same problem, Window

**Comment by mujiannan** [comment]
The memory usage increased quickly, continuously.
