### ISSUE TITLE
Comment Problem

### ISSUE THREAD

**Issue by bobyuxinyang** [ljcoder2015/obsidian-sheet-plus#32]
**Describe the bug**
When adding more than one comment to a cell, the comments will become chaotic after reloading the file.

**To Reproduce**
1. Add at least two comments to any cell.
2. Close the file, and then reopen it.
3. See error: a. edit or remote button disappear  b. duplicated comments will be generated

**Expected behavior**
After reopening, you can see the correct comments and modify them.

**Screenshots**
After adding comments(it works fine)
![image](https://github.com/user-attachments/assets/cad5ff67-8aef-490e-b059-8bbaf2a9df79)

After reopening the file(here's the bug)
![image](https://github.com/user-attachments/assets/3d3ae78e-cbbd-4bee-9e0c-712412555a0c)

**Device (please complete the following information):**
 - OS: macOS

**Obsidian (please complete the following information):**
 - Version 1.6.7

**Additional context**

**Comment by ljcoder2015** [comment]
fix 1.4.1
