### ISSUE TITLE
the sheet plus can not open in ipados

### ISSUE THREAD

**Issue by violentrant** [ljcoder2015/obsidian-sheet-plus#33]
**Describe the bug**

the sheet plus can not open in ipados

**To Reproduce**

**Expected behavior**
hope it can use correctly

**Screenshots**

**Device (please complete the following information):**
ipad os 17

**Obsidian  sheet plus 1.3.3

**Comment by ljcoder2015** [comment]
fix [1.3.4](https://github.com/ljcoder2015/obsidian-sheet-plus/releases/tag/1.3.4)
