### ISSUE TITLE
sheet plus overwriting the 'process' object

### ISSUE THREAD

**Issue by scooper4711** [ljcoder2015/obsidian-sheet-plus#34]
**Describe the bug**
I originally opened https://github.com/Vinzent03/obsidian-git/issues/761 because it was failing to execute `process.cwd()`. As it turns out, the process object looks one way without the sheets plus plugin loaded, and looks completely different with the plugin installed. 

**To Reproduce**
1. prior to installing sheets plus, in the inspector, execute `process.constructor.name`.
2. notice that the value returned is `process`.
3. install and activate sheets plus. 
4. re-execute that code.
5. notice that the signature of process has changed, and the result returned by `process.constructor.name` is now Object.

**Expected behavior**
Process is a node variable, and should keep its class and associated methods.

**Device (please complete the following information):**
 - OS: MacOS
 - Version 14.5

**Obsidian (please complete the following information):**
 - Version 1.6.7

**Comment by scooper4711** [comment]
Looks like you are both importing different process definitions.

**Comment by ljcoder2015** [comment]
fix [1.3.5](https://github.com/ljcoder2015/obsidian-sheet-plus/releases/tag/1.3.5)
