### ISSUE TITLE
result of CONCAT function is blank

### ISSUE THREAD

**Issue by Yenine** [ljcoder2015/obsidian-sheet-plus#39]
**Describe the bug**
CONCAT function does not work, the unit just show blank
**To Reproduce**
use concat function

**Screenshots**
![image](https://github.com/user-attachments/assets/cd6f5b01-3999-4e97-a892-e9955957f124)

**Device (please complete the following information):**
 - OS: Windows11

**Obsidian (please complete the following information):**
 - Version 1.6.7

**Comment by ljcoder2015** [comment]
fix
