### ISSUE TITLE
After directly copying the "Copy embedded link," it shows up as blank.

### ISSUE THREAD

**Issue by cyuan68** [ljcoder2015/obsidian-sheet-plus#47]
**Describe the bug**
After directly copying the "Copy embedded link," it shows up as blank.

**To Reproduce**
1. Click on Click on "Copy embedded link."
2. Directly paste it into the newly created .md file.
3. See error

**Expected behavior**
The expected result is the same as the GIF demonstration of the embedded link in the README file, but the outcome is blank.

**Screenshots**

versions of Obsidian, Sheet-Plus version 1.4.1 and above.
![sheet-plus错误1](https://github.com/user-attachments/assets/dc7f9aca-c333-40cf-825c-d2b7d5f32e30)

versions of Obsidian, Sheet-Plus version 1.3.6
![sheet-plus错误2](https://github.com/user-attachments/assets/9710d475-717b-4e70-bca7-45d97f42a5ba)

**Device (please complete the following information):**
 - OS: Windows
 - sheet-plus Version 1.4.1~1.4.3

**Obsidian (please complete the following information):**
 - Version 1.5.12 and 1.7.4

**Additional context**

when I tried installing different versions of Obsidian, it still displayed as blank.

when I tried installing different versions of Sheet-Plus, it only worked in versions 1.3.6 and 1.4.0.

**Comment by TopWinStudio1984** [comment]
I have the same issue and look forward to getting a solution. Thank you very much.
