### ISSUE TITLE
Update the univer version to v0.5.0

### ISSUE THREAD

**Issue by karlsbeard** [ljcoder2015/obsidian-sheet-plus#53]
**Is your feature request related to a problem? Please describe.**
univer has published version 0.5 and the version has many new features, especially the count of formula function.
**Describe the solution you'd like**

update univer version 

**Describe alternatives you've considered**
I can help update the version because the version 0.5 has many break changes.

**Additional context**

**Comment by kingman1102** [comment]
Thank your team so much!
I haven't been able to explore all the features yet. But if possible please add the "Format" when right click on the cell to be edited
Without I have a question "Have your team stopped updating the "Excel" project and replaced it with "Sheet Plus"?

**Comment by karlsbeard** [comment]
> Thank your team so much! I haven't been able to explore all the features yet. But if possible please add the "Format" when right click on the cell to be edited Without I have a question "Have your team stopped updating the "Excel" project and replaced it with "Sheet Plus"?

sry, I am not a developer on this team. In addition, I found that the "Excel" project introduction is indeed no longer maintained.

**Comment by kingman1102** [comment]
Pls update more some features:
- Add the "Format" when right click on the cell
- Click edge of cell will Fit to data (as Microsoft Excel). Current Fit for data only available on Title of column
- When I type "6 A" in cell, it convert to "6:00 AM". Then I must format cell to "General"
- Can not use hotkey as F2 to edit cell. So each edit cell need double click to cell
Thanks!

**Comment by ljcoder2015** [comment]
Version 1.5.0 has been updated
