### ISSUE TITLE
sumif formular doesn't work

### ISSUE THREAD

**Issue by dcww654** [ljcoder2015/obsidian-sheet-plus#55]
https://github.com/user-attachments/assets/94486769-57bf-4a83-a89d-94854891fb37

**Comment by ljcoder2015** [comment]
<img width="589" alt="image" src="https://github.com/user-attachments/assets/bdf3d252-9154-458c-b74e-d3df545897b6" />
[1.5.1](https://github.com/ljcoder2015/obsidian-sheet-plus/releases/tag/1.5.1)  working well
