### ISSUE TITLE
Memory uses rapidly increases when enabling plugin in Windows 10

### ISSUE THREAD

**Issue by BlackUdon** [ljcoder2015/obsidian-sheet-plus#56]
**Describe the bug**
Memory uses rapidly increases when enabling the plugin while running Obsidian 1.7.7 in Windows 10. This also happens when in Sandbox Vault.

**To Reproduce**
1. Run command "Open sandbox vault"
2. Download and enable plugin
3. look at memory usage in Task Manager

**Expected behavior**
Low memory usage 

**Device (please complete the following information):**
 - OS: Windows 10

**Obsidian (please complete the following information):**
 - Version 1.7.7

**Comment by ljcoder2015** [comment]
fix 1.5.1
